DROP INDEX idx_device_model_required_snaps_deleted_at;
DROP INDEX idx_device_model_required_snaps_name;
DROP TABLE device_model_required_snaps;
DROP INDEX idx_device_models_deleted_at;
DROP TABLE device_models;