version: '3'

dotenv: [ '{{.HOME}}/.device-management-env', '.env' ]


tasks:
  add-migration:
    desc: Add a migration
    cmds:
      - migrate create -ext sql -dir db/migrations $MIGRATION_NAME
  migrate-up:
    desc: Run migrations (up)
    cmds:
      - |
        if [ -z $N ]; then
          echo N must be set, either a number of migrations or "all"
          exit 1
        fi
        if [ $N == "all" ]; then
          migrate -database $MANAGEMENT_POSTGRES_DATASOURCE -path ./db/migrations up
          exit 0
        else
          migrate -database $MANAGEMENT_POSTGRES_DATASOURCE -path ./db/migrations up $N
          exit 0
        fi

  migrate-down:
    desc: Run migrations (down)
    cmds:
      - |
        if [ -z $N ]; then
          echo N must be set, either a number of migrations or "all"
          exit 1
        fi
        if [ $N == "all" ]; then
          migrate -database $MANAGEMENT_POSTGRES_DATASOURCE -path ./db/migrations down
          exit 0
        else
          migrate -database $MANAGEMENT_POSTGRES_DATASOURCE -path ./db/migrations down $N
          exit 0
        fi