// Code generated by schema-generate. DO NOT EDIT.

package messages

// SchemaDefinitionsForTheRESTAPI
type SchemaDefinitionsForTheRESTAPI interface{}

// DeviceLogs
type DeviceLogs struct {

	// The max number of logs to pull down from snapd api.
	Limit int `json:"limit,omitempty"`

	// A presigned S3 url to PUT logs to
	Url string `json:"url,omitempty"`
}

// DeviceUser
type DeviceUser struct {

	// What action to take on the provided user
	Action string `json:"action,omitempty"`

	// Ubuntu SSO email to use when creating a user
	Email string `json:"email,omitempty"`

	// Force the creation of the user even if the device is managed by a single user
	ForceManaged bool `json:"force-managed,omitempty"`

	// Flag to indicate that the user being created should have sudoer access
	Sudoer bool `json:"sudoer,omitempty"`

	// What username to remove from the device
	Username string `json:"username,omitempty"`
}

// SnapService
type SnapService struct {

	// A list of services within the snap to take action on (or empty to apply to all)
	Services []string `json:"services,omitempty"`
}

// SnapSnapshot
type SnapSnapshot struct {

	// A presigned S3 url to PUT a snapshot of a snap to
	Url string `json:"url,omitempty"`
}

// SnapUpdate
type SnapUpdate struct {
	Data string `json:"data,omitempty"`
}
