apiVersion: v1
kind: Secret
metadata:
  name: management-secrets
stringData:
  static-token: ${STATIC_CLIENT_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-config
  labels:
    app: management
data:
  HOST: "${HOST}"
  SCHEME: "${SCHEME}"