apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  labels:
    app: postgres
data:
  iot.conf: |

    connection_messages false
    log_type error
    log_type warning
    log_timestamp_format %Y-%m-%dT%H:%M:%S

    port 8883
    cafile /mosquitto/certs/ca.crt
    keyfile /mosquitto/certs/server.key
    certfile /mosquitto/certs/server.crt

    require_certificate true
    use_identity_as_username true

    listener 31883
    allow_anonymous true
    #password_file /mosquitto/passwd_mqtt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  selector:
    matchLabels:
      app: mqtt
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt
        tier: backend
        track: stable
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config
            - name: certs
              mountPath: /mosquitto/certs
          ports:
            - containerPort: 8883
            - containerPort: 31883
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 31883
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 31883
            timeoutSeconds: 2
      volumes:
        - name: config-volume
          configMap:
            name: mqtt-config
            items:
              - key: iot.conf
                path: mosquitto.conf
        - name: certs
          secret:
            secretName: mqtt-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  selector:
    app: mqtt
    tier: backend
  ports:
    - name: mqtts
      port: 8883
      protocol: TCP