name: dmscore

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go install github.com/go-task/task/v3/cmd/task@latest
      - run: task install-mockery
      - run: task install-schema-generate

      - run: task generate-message-structs

      - name: Build
        run: go build -v bin/dmscore/dmscore.go

      - name: Test
        run: task run-tests